title:            Will DiBiagio
description:      who is Will DiBiagio
url:              http://willdibiagi0.com
permalink:        pretty
timezone:         America/Los_Angeles
sass:
  sass_dir: assets
  style: :compressed
collections:
  - notes
